# Generated by Django 5.1.7 on 2025-03-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_post_likes_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_code',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
